name: API Testing

on:
  workflow_dispatch:
      inputs:
        env:
          description: 'Run test environment'
          required: true
          default: 'DEMO'

env:
  demo: "DEMO"
  staging: "STAGING"

jobs:
  apiTestRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run test
        run: mvn clean test -Dtestng.dtd.http=true -Denvironment=${{ github.event.inputs.env }}
